### ISSUE TITLE
Backslashes are missing in the file paths when run on Windows environment.

### ISSUE THREAD

**Issue by petrunov** [stevenwilshaw/mocha-image-compiler#2]
i.e. 
C:\app\images\photo.png

import photo from 'photo'

console.log(photo) => C:appimagesphoto.png

**Comment by jonvuri** [comment]
A related issue, also caused by the backslashes not being escaped: when the path contains the sequence `\u`, a syntax error is thrown since it looks like the start of a Unicode escape sequence:

```
C:\Dev\ceg-ui\src\assets\up-arrow.svg:1
(function (exports, require, module, __filename, __dirname) { module.exports = 'C:\Dev\ui\src\assets\up-arrow.svg'
                                                                                                        ^^^^^^
SyntaxError: Invalid Unicode escape sequence
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.loader (C:\Dev\ui\node_modules\mocha-image-compiler\index.js:2:19)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Dev/ceg-ui/src/components/browse/BrowsePage.jsx:15:1)
    at Module._compile (module.js:556:32)
    at loader (C:\Dev\ceg-ui\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (C:\Dev\ceg-ui\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Dev/ceg-ui/src/components/browse/BrowsePage.spec.js:3:1)
    at Module._compile (module.js:556:32)
    at loader (C:\Dev\ceg-ui\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Dev\ceg-ui\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at C:\Dev\ceg-ui\node_modules\mocha\lib\mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Dev\ceg-ui\node_modules\mocha\lib\mocha.js:219:14)
    at Mocha.run (C:\Dev\ceg-ui\node_modules\mocha\lib\mocha.js:487:10)
    at Object.<anonymous> (C:\Dev\ceg-ui\node_modules\mocha\bin\_mocha:458:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
